name: 'gitbook action for publishing new link on readme for each new addition'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v3
    
    - name: "segment files seperately when uploaded"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          global_template_repository: Debond-protocols/docs
          files: |
            README.md
            **.md=docs/**.md

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


